### ISSUE TITLE
Opt-out request for duaneking

### ISSUE THREAD

**Issue by duaneking** [bigcode-project/opt-out-v2#10]
I request that ALL DATA affiliated with this username is removed from The Stack:

This includes but it not limited to:

 - Commits
 - GitHub issue

 - duaneking/IdentityServer4.AccessTokenValidation
 - duaneking/IdentityServer4.AspNetIdentity
 - duaneking/IdentityServer4.Demo
 - duaneking/IdentityServer4.EntityFramework
 - duaneking/IdentityServer4.EntityFramework.Storage
 - duaneking/IdentityServer4.Quickstart.UI
 - duaneking/IdentityServer4.Quickstart.UI.AspNetIdentity
 - duaneking/IdentityServer4.Storage
 - duaneking/IdentityServer4.Templates
 - duaneking/Superscribe
 - duaneking/WheelMUD
 - duaneking/awesome-falsehood
 - duaneking/big-list-of-naughty-strings
 - duaneking/drawio
 - duaneking/hematite
 - duaneking/memoize-cache
 - duaneking/minecraft-ondemand
 - duaneking/no-fucking-thanks
 - duaneking/oauthlib
 - duaneking/pycraft
 - duaneking/quartznet
 - duaneking/rockstar
 - duaneking/serverless-examples-cached-rds-ws
 - duaneking/unburyme

I did not consent to have my work included and consider AI being trained on me without my consent to be worse than theft.

From my perspective as the license owner, as I did  not expressly grant AI the right to use my code, I have not done so, so any attempt to use my code for AI is a violation of my more human focused terms.

**Comment by duaneking** [comment]
My biggest issue with this project is the violation of GPL.

**Comment by duaneking** [comment]
And for the record, I don't believe that asking for forgiveness is better than asking for for permission here. You literally stole people's code without their consent.

**Comment by cheld** [comment]
@duaneking hello, I am not part of big code project. I am answering because, your statement is incorrect. Copyright does not include reading and processing data. As the name suggests, only copying. Literally speaking, you can go in a book store take out any book of the shelf, read it and put it back, leave the store and don't pay anything. Again reading and processing is not part of copyright and not covered by license. They don't need license. Even more, when you signed up for Github, then you accepted the Github EULA. This EULA explicitly allows the right to read public repositories. 

You see, the licenses you have picked are irrelevant in this subject. (This may not be true when code is reprocuded without attribution later on in the generation process. But this is different topic)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
